iceberg:
  tables:
    - name: "add_lead"
      namespace: "ns_rsa"
      warehouse: "development"
      catalog_name: "development"
      columns: ['stt', 'vehicle_owner_name', 'phone', 'address', 'license_plate', 'vehicle_brand', 'model_type', 'certificate_number', 'valid_from', 'valid_to', 'certificate_paper', 'product_package', 'rsa_type', 'processing_date']
      filters:
        processing_date: "2025-01-01"
    # - name: "rsa_lead"
    #   namespace: "ns_rsa"
    #   warehouse: "lnd_tdc"
    #   catalog_name: "lnd_tdc"
    #   columns: ['stt', 'vehicle_owner_name', 'phone', 'address', 'license_plate', 'vehicle_brand', 'model_type', 'certificate_number', 'valid_from', 'valid_to', 'certificate_paper', 'product_package', 'processing_date']
    #   processing_date: "2025-01-01"